apiVersion: apps/v1
kind: Deployment
metadata: 
  name: video-streaming       #naming hte pod
spec:
  replicas: 1
  selector:               #data for the pod we are managing
    matchLabels: 
      app: video-streaming      #how its selecting the pod we are managing
  template:           #data for pod we are creaming
    metadata:
      labels:
        app: video-streaming
    spec:
      containers:
      - name: video-streaming
      # image: video-streaming:1
        # image: nkmt1.azurecr.io/video-streaming:3
        image: $CONTAINER_REGISTRY.video-streaming/$VERSION   # set env variables that are put in with envsubst command line so these are not hardcoded in CD
        # imagePullPolicy: Never        #dont find the image online, its local
        imagePullPolicy: Always       #ALWAYS DO ALWAYS #IfNotPresent    #if not in cluster, pull from container registry (get to cluster this way initially)
        env:
        - name: PORT
          value: "4000"

---
apiVersion: v1
kind: Service
metadata:
  name: video-streaming
spec:
  selector: 
    app: video-streaming      #connected to the pod
  # type: NodePort      # default is clusterIP which is only available within cluster
  type: LoadBalancer             #allocate an IP so we can access MS from outside
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      # nodePort: 30000       # choose port in range 30000-32767
