# FROM node:18.5.0-alpine
FROM --platform=linux/amd64 node :18.5.0-alpine    

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --only=production
COPY ./src ./src
COPY ./videos ./videos
CMD npm start
# CMD npx wait-port rabbit:5672 && \
    # npm start