name: CI

on:
  push:
    branches:
      - master
    paths:
      - video-streaming/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3   # installs node for workflow
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: ./video-streaming/package-lock.json

    - run: npm ci     #this is the CI pipeline command
    - run: npm test   #automated test - came from template - next chapter shows how to implement